name: Required Status Check

on: [pull_request]

permissions:
  contents: read  # Allows the workflow to read the repository contents

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple check
        run: echo "Status check passed!"
